In [1]:
import cv2
import numpy as np
import os
import math
import matplotlib.pyplot as plt

In [2]:
raw_img = cv2.imread('lena.bmp', cv2.IMREAD_GRAYSCALE)

In [ ]:
def Robert(img,threshold):
    ker_1 = np.array([[-1, 0], [0, 1]])
    ker_2 = np.array([[0, -1], [1, 0]])
    pass

In [ ]:
def Prewitt(img,threshold):
    padded = cv2.copyMakeBorder(raw_img,2,2,2,2,cv2.BORDER_REFLECT)
    pass

In [ ]:
def Sobel():
    pass

In [ ]:
def Frei_and_Chen():
    pass

In [ ]:
def Kirsch():
    pass

In [ ]:
def Robinson():
    pass

In [ ]:
def Nevatia_Babu():
    pass

In [20]:
ker = np.array([[1, 2,3], [4, 5,6],[7,8,9],[10,11,12]])
print(ker)
print(ker.shape)
print(ker.shape[0])
for row in range(ker.shape[0]):
    for col in range(ker.shape[1]):
        print(ker[row][col])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
4
1
2
3
4
5
6
7
8
9
10
11
12
